/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 5, 2023 at 3:05:04 PM Central European Summer Time
* Operating System: Version 14.8 (Build 18H17)
* Image Source: /usr/libexec/terminusd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSData;

@interface NRDLDKeys : NSObject <NSCopying, NSSecureCoding> {

	NSData* _remotePublicKey;
	NSData* _localPublicKey;
	NSData* _localPrivateKey;
	NSData* _sharedSecret;
	NSData* _localPublicTLVEncryptedWithIDS;
	NSData* _dhLocalPublic;
	NSData* _dhLocalPrivate;

}

@property (nonatomic,retain) NSData * remotePublicKey;                             //@synthesize remotePublicKey=_remotePublicKey - In the implementation block
@property (nonatomic,retain) NSData * localPublicKey;                              //@synthesize localPublicKey=_localPublicKey - In the implementation block
@property (nonatomic,retain) NSData * localPrivateKey;                             //@synthesize localPrivateKey=_localPrivateKey - In the implementation block
@property (nonatomic,retain) NSData * sharedSecret;                                //@synthesize sharedSecret=_sharedSecret - In the implementation block
@property (nonatomic,retain) NSData * localPublicTLVEncryptedWithIDS;              //@synthesize localPublicTLVEncryptedWithIDS=_localPublicTLVEncryptedWithIDS - In the implementation block
@property (nonatomic,retain) NSData * dhLocalPublic;                               //@synthesize dhLocalPublic=_dhLocalPublic - In the implementation block
@property (nonatomic,retain) NSData * dhLocalPrivate;                              //@synthesize dhLocalPrivate=_dhLocalPrivate - In the implementation block
@property (nonatomic,readonly) BOOL isEmpty; 
+(BOOL)supportsSecureCoding;
-(BOOL)generateNewKeys;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEmpty;
-(NSData *)remotePublicKey;
-(void)setRemotePublicKey:(NSData *)arg1 ;
-(NSData *)localPublicKey;
-(void)setLocalPublicKey:(NSData *)arg1 ;
-(NSData *)localPrivateKey;
-(void)setLocalPrivateKey:(NSData *)arg1 ;
-(NSData *)sharedSecret;
-(void)setSharedSecret:(NSData *)arg1 ;
-(NSData *)localPublicTLVEncryptedWithIDS;
-(void)setLocalPublicTLVEncryptedWithIDS:(NSData *)arg1 ;
-(NSData *)dhLocalPublic;
-(void)setDhLocalPublic:(NSData *)arg1 ;
-(NSData *)dhLocalPrivate;
-(void)setDhLocalPrivate:(NSData *)arg1 ;
@end
