/*
* This header is generated by classdump-dyld 1.0
* on Friday, May 5, 2023 at 3:05:04 PM Central European Summer Time
* Operating System: Version 14.8 (Build 18H17)
* Image Source: /usr/libexec/terminusd
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSObject, NSUUID, NWNetworkAgentRegistration, NSMutableArray, NSString, NSData;

@interface NRLink

@property (nonatomic,retain) NSData * usedProxyNotifyPayload;                                  
@property (assign,nonatomic) unsigned long long linkReadyStartTime;                            
@property (assign,nonatomic) double linkTotalReadyTimeInSec;                                   
@property (assign,nonatomic) unsigned short linkMTU;                                           
@property (nonatomic,readonly) unsigned char state;                                            
@property (nonatomic,readonly) unsigned char type;                                             
@property (nonatomic,readonly) unsigned long long identifier;                                  
@property (nonatomic,readonly) BOOL ikeClassCEstablished;                                      
@property (nonatomic,readonly) BOOL ikeClassDEstablished;                                      
@property (nonatomic,readonly) BOOL peerAvailabilityCheckInProgress;                           
@property (assign,nonatomic) BOOL noTransport;                                                 
@property (assign,nonatomic) BOOL isPrimary;                                                   
@property (assign,nonatomic) BOOL suspendWhenReady;                                           
@property (assign,nonatomic) BOOL hasRouteRulePolicy;                                          
@property (nonatomic,retain) NSMutableArray * policyIDs;                                       
@property (nonatomic,retain) NSString * policyIdentifierString;                                
@property (nonatomic,readonly) BOOL startRequested;                                            
@property (assign,nonatomic) unsigned short metric;                                            
@property (nonatomic,readonly) NSUUID * nrUUID;                                                
-(void)setState:(unsigned char)arg1 ;
-(void)setType:(unsigned char)arg1 ;
-(void)setIdentifier:(unsigned long long)arg1 ;
-(void)setNrUUID:(NSUUID *)arg1 ;
-(void)setStartRequested:(BOOL)arg1 ;
-(void)invalidateLink;
-(void)invalidateIKESession:(id*)arg1 ;
-(void)invalidateIKESessionForClass:(unsigned char)arg1 ;
-(void)unregisterProxyAgent;
-(void)checkProxyAgentWithForceUpdate:(BOOL)arg1 ;
-(id)initLinkWithQueue:(id)arg1 linkDelegate:(id)arg2 nrUUID:(id)arg3 ;
-(id)copyDescriptionInner;
-(id)copyDescription;
-(id)description;
-(id)copyShortDescriptionInner;
-(id)copyShortDescription;
-(BOOL)start;
-(BOOL)suspend;
-(BOOL)resume;
-(unsigned short)metric;
-(id)copyStatusString;
-(BOOL)cancelWithReason:(id)arg1 ;
-(BOOL)sendControlData:(id)arg1 ;
-(void)reportEvent:(int)arg1 details:(id)arg2 ;
-(void)reportEvent:(int)arg1 detailsFormat:(id)arg2 ;
-(void)reportEvent:(int)arg1 ;
-(BOOL)changeStateTo:(unsigned char)arg1 details:(id)arg2 ;
-(BOOL)changeStateTo:(unsigned char)arg1 detailsFormat:(id)arg2 ;
-(BOOL)changeStateTo:(unsigned char)arg1 ;
-(void)setLinkMTU:(unsigned short)arg1 ;
-(void)dealloc;
-(void)setIsPrimary:(BOOL)arg1 ;
-(void)setInterfaceAvailabilityIfApplicable;
-(void)setInterfaceAvailabilityForcedWithInterfaceName:(id)arg1 ;
-(BOOL)setInterfaceSubfamily;
-(BOOL)setNoACKPrioritization;
-(void)checkPeerAvailabilityWithForceAggressive:(BOOL)arg1 ;
-(void)refreshCompanionProxyAgent;
-(void)removePolicies;
-(unsigned char)state;
-(unsigned char)type;
-(unsigned long long)identifier;
-(BOOL)ikeClassCEstablished;
-(BOOL)ikeClassDEstablished;
-(double)linkTotalReadyTimeInSec;
-(void)setLinkTotalReadyTimeInSec:(double)arg1 ;
-(BOOL)peerAvailabilityCheckInProgress;
-(BOOL)noTransport;
-(void)setNoTransport:(BOOL)arg1 ;
-(BOOL)isPrimary;
-(BOOL)suspendWhenReady;
-(void)setSuspendWhenReady:(BOOL)arg1 ;
-(BOOL)hasRouteRulePolicy;
-(void)setHasRouteRulePolicy:(BOOL)arg1 ;
-(NSMutableArray *)policyIDs;
-(void)setPolicyIDs:(NSMutableArray *)arg1 ;
-(NSString *)policyIdentifierString;
-(void)setPolicyIdentifierString:(NSString *)arg1 ;
-(BOOL)startRequested;
-(unsigned short)linkMTU;
-(void)setMetric:(unsigned short)arg1 ;
-(NSUUID *)nrUUID;
-(NSData *)usedProxyNotifyPayload;
-(void)setUsedProxyNotifyPayload:(NSData *)arg1 ;
-(unsigned long long)linkReadyStartTime;
-(void)setLinkReadyStartTime:(unsigned long long)arg1 ;
@end
