/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:33:47 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/Frameworks/Network.framework/Network
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

//#import <Network/Network-Structs.h>
//#import <Network/NWHostEndpoint.h>

@class NSString, NSData;

@interface NWAddressEndpoint //: NWHostEndpoint

@property (nonatomic,readonly) BOOL isWildcard; 
@property (nonatomic,readonly) BOOL isLoopback; 
@property (nonatomic,readonly) NSString * addressString; 
@property (nonatomic,readonly) NSString * addressStringNoPort; 
@property (nonatomic,readonly) NSData * addressData; 
@property (nonatomic,readonly) const struct sockaddr* address; 
@property (nonatomic,readonly) unsigned long long addressFamily; 
+(unsigned)endpointType;
+(id)endpointWithHostname:(id)arg1 port:(id)arg2 ;
+(id)endpointWithAddress:(const struct sockaddr*)arg1 ;
-(BOOL)isWildcard;
-(BOOL)isLoopback;
-(NSString *)addressString;
-(NSData *)addressData;
-(id)descriptionWithIndent:(int)arg1 showFullContent:(BOOL)arg2 ;
-(const struct sockaddr*)address;
-(NSString *)addressStringNoPort;
-(unsigned long long)addressFamily;
-(id)ethernetAddress;
@end